// <auto-generated />
using System;
using CarRentalApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalApp.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    [Migration("20240413111029_VRM6")]
    partial class VRM6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CarRentalApp.Models.CarModel", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<double>("DailyRate")
                        .HasColumnType("double");

                    b.Property<string>("IsAvailable")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Capacity = 4,
                            DailyRate = 55.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc032",
                            Make = "Chevrolet",
                            Model = "Bolt EV",
                            Type = "Hatchback",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 2,
                            Capacity = 6,
                            DailyRate = 70.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc035",
                            Make = "Acura",
                            Model = "MDX",
                            Type = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 3,
                            Capacity = 4,
                            DailyRate = 40.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc036",
                            Make = "Subaru",
                            Model = "BRZ",
                            Type = "Coupe",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 4,
                            Capacity = 6,
                            DailyRate = 45.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc065",
                            Make = "Jeep",
                            Model = "Grand Wagoneer",
                            Type = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 5,
                            Capacity = 4,
                            DailyRate = 60.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc075",
                            Make = "GMC",
                            Model = "Hummer EV",
                            Type = "Pickup",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 6,
                            Capacity = 6,
                            DailyRate = 70.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc084",
                            Make = "Chevrolet",
                            Model = "Traverse",
                            Type = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 7,
                            Capacity = 6,
                            DailyRate = 55.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc088",
                            Make = "Chevrolet",
                            Model = "Equinox",
                            Type = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 8,
                            Capacity = 6,
                            DailyRate = 70.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc119",
                            Make = "Kia",
                            Model = "Sorento",
                            Type = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 9,
                            Capacity = 6,
                            DailyRate = 50.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc122",
                            Make = "Nissan",
                            Model = "Pathfinder",
                            Type = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 10,
                            Capacity = 4,
                            DailyRate = 50.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc178",
                            Make = "Mercedes-Benz",
                            Model = "C-Class",
                            Type = "Coupe",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 11,
                            Capacity = 6,
                            DailyRate = 70.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc203",
                            Make = "Hyundai",
                            Model = "Tucson",
                            Type = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 12,
                            Capacity = 6,
                            DailyRate = 45.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc268",
                            Make = "Volkswagen",
                            Model = "Tiguan",
                            Type = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 13,
                            Capacity = 6,
                            DailyRate = 65.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc293",
                            Make = "Mitsubishi",
                            Model = "Eclipse Cross",
                            Type = "SUV",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 14,
                            Capacity = 4,
                            DailyRate = 60.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc299",
                            Make = "Honda",
                            Model = "Civic",
                            Type = "Sedan",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 15,
                            Capacity = 4,
                            DailyRate = 55.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc375",
                            Make = "Nissan",
                            Model = "Frontier Crew Cab",
                            Type = "Pickup",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 16,
                            Capacity = 4,
                            DailyRate = 40.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc001",
                            Make = "Audi",
                            Model = "A6 allroad",
                            Type = "Wagon",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 17,
                            Capacity = 4,
                            DailyRate = 50.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc003",
                            Make = "Honda",
                            Model = "Accord",
                            Type = "Sedan",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 18,
                            Capacity = 4,
                            DailyRate = 55.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc004",
                            Make = "MAZDA",
                            Model = "MAZDA3",
                            Type = "Hatchback,Sedan",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 19,
                            Capacity = 6,
                            DailyRate = 60.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc005",
                            Make = "Volkswagen",
                            Model = "Atlas Cross Sport",
                            Type = "SUV",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 20,
                            Capacity = 4,
                            DailyRate = 40.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc008",
                            Make = "Porsche",
                            Model = "Panamera",
                            Type = "Sedan",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 21,
                            Capacity = 6,
                            DailyRate = 45.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc009",
                            Make = "Jeep",
                            Model = "Grand Cherokee L",
                            Type = "SUV",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 22,
                            Capacity = 6,
                            DailyRate = 70.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc014",
                            Make = "Cadillac",
                            Model = "XT6",
                            Type = "SUV",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 23,
                            Capacity = 4,
                            DailyRate = 40.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc015",
                            Make = "Toyota",
                            Model = "Corolla",
                            Type = "Sedan",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 24,
                            Capacity = 4,
                            DailyRate = 60.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc019",
                            Make = "BMW",
                            Model = "3 Series",
                            Type = "Sedan",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 25,
                            Capacity = 4,
                            DailyRate = 70.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc021",
                            Make = "Kia",
                            Model = "Stinger",
                            Type = "Sedan",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 26,
                            Capacity = 4,
                            DailyRate = 55.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc025",
                            Make = "Toyota",
                            Model = "Tundra Double Cab",
                            Type = "Pickup",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 27,
                            Capacity = 4,
                            DailyRate = 60.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc026",
                            Make = "Kia",
                            Model = "Forte",
                            Type = "Sedan",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 28,
                            Capacity = 6,
                            DailyRate = 70.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc028",
                            Make = "Subaru",
                            Model = "Outback",
                            Type = "SUV",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 29,
                            Capacity = 6,
                            DailyRate = 40.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc029",
                            Make = "Cadillac",
                            Model = "XT4",
                            Type = "SUV",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 30,
                            Capacity = 6,
                            DailyRate = 50.0,
                            IsAvailable = "TRUE",
                            LicensePlate = "abc031",
                            Make = "Mercedes-Benz",
                            Model = "G-Class",
                            Type = "SUV",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.RenterModel", b =>
                {
                    b.Property<int>("RenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RenterId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("RenterId");

                    b.ToTable("Renters");

                    b.HasData(
                        new
                        {
                            RenterId = 1,
                            Address = "1970 Napa Ct.",
                            Email = "ken0@adventure-works.com",
                            FName = "Ken",
                            LName = "Sánchez",
                            PhoneNumber = "697-555-0142",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 2,
                            Address = "9833 Mt. Dias Blv.",
                            Email = "terri0@adventure-works.com",
                            FName = "Terri",
                            LName = "Duffy",
                            PhoneNumber = "819-555-0175",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 3,
                            Address = "7484 Roundtree Drive",
                            Email = "roberto0@adventure-works.com",
                            FName = "Roberto",
                            LName = "Tamburello",
                            PhoneNumber = "212-555-0187",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 4,
                            Address = "9539 Glenside Dr",
                            Email = "rob0@adventure-works.com",
                            FName = "Rob",
                            LName = "Walters",
                            PhoneNumber = "612-555-0100",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 5,
                            Address = "1226 Shoe St.",
                            Email = "gail0@adventure-works.com",
                            FName = "Gail",
                            LName = "Erickson",
                            PhoneNumber = "849-555-0139",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 6,
                            Address = "1399 Firestone Drive",
                            Email = "jossef0@adventure-works.com",
                            FName = "Jossef",
                            LName = "Goldberg",
                            PhoneNumber = "122-555-0189",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 7,
                            Address = "5672 Hale Dr.",
                            Email = "dylan0@adventure-works.com",
                            FName = "Dylan",
                            LName = "Miller",
                            PhoneNumber = "181-555-0156",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 8,
                            Address = "6387 Scenic Avenue",
                            Email = "diane1@adventure-works.com",
                            FName = "Diane",
                            LName = "Margheim",
                            PhoneNumber = "815-555-0138",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 9,
                            Address = "8713 Yosemite Ct.",
                            Email = "gigi0@adventure-works.com",
                            FName = "Gigi",
                            LName = "Matthew",
                            PhoneNumber = "185-555-0186",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 10,
                            Address = "250 Race Court",
                            Email = "michael6@adventure-works.com",
                            FName = "Michael",
                            LName = "Raheem",
                            PhoneNumber = "330-555-2568",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 11,
                            Address = "1318 Lasalle Street",
                            Email = "ovidiu0@adventure-works.com",
                            FName = "Ovidiu",
                            LName = "Cracium",
                            PhoneNumber = "719-555-0181",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 12,
                            Address = "5415 San Gabriel Dr.",
                            Email = "thierry0@adventure-works.com",
                            FName = "Thierry",
                            LName = "D'Hers",
                            PhoneNumber = "168-555-0183",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 13,
                            Address = "9265 La Paz",
                            Email = "janice0@adventure-works.com",
                            FName = "Janice",
                            LName = "Galvin",
                            PhoneNumber = "473-555-0117",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 14,
                            Address = "8157 W. Book",
                            Email = "michael8@adventure-works.com",
                            FName = "Michael",
                            LName = "Sullivan",
                            PhoneNumber = "465-555-0156",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 15,
                            Address = "4912 La Vuelta",
                            Email = "sharon0@adventure-works.com",
                            FName = "Sharon",
                            LName = "Salavaria",
                            PhoneNumber = "970-555-0138",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 16,
                            Address = "40 Ellis St.",
                            Email = "david0@adventure-works.com",
                            FName = "David",
                            LName = "Bradley",
                            PhoneNumber = "913-555-0172",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 17,
                            Address = "6696 Anchor Drive",
                            Email = "kevin0@adventure-works.com",
                            FName = "Kevin",
                            LName = "Brown",
                            PhoneNumber = "150-555-0189",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 18,
                            Address = "1873 Lion Circle",
                            Email = "john5@adventure-works.com",
                            FName = "John",
                            LName = "Wood",
                            PhoneNumber = "486-555-0150",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 19,
                            Address = "3148 Rose Street",
                            Email = "mary2@adventure-works.com",
                            FName = "Mary",
                            LName = "Dempsey",
                            PhoneNumber = "124-555-0114",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 20,
                            Address = "6872 Thornwood Dr.",
                            Email = "wanida0@adventure-works.com",
                            FName = "Wanida",
                            LName = "Benshoof",
                            PhoneNumber = "708-555-0141",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 21,
                            Address = "5747 Shirley Drive",
                            Email = "terry0@adventure-works.com",
                            FName = "Terry",
                            LName = "Eminhizer",
                            PhoneNumber = "138-555-0118",
                            ZipCode = 98011
                        },
                        new
                        {
                            RenterId = 22,
                            Address = "636 Vine Hill Way",
                            Email = "sariya0@adventure-works.com",
                            FName = "Sariya",
                            LName = "Harnpadoungsataya",
                            PhoneNumber = "399-555-0176",
                            ZipCode = 97205
                        },
                        new
                        {
                            RenterId = 23,
                            Address = "6657 Sand Pointe Lane",
                            Email = "mary0@adventure-works.com",
                            FName = "Mary",
                            LName = "Gibson",
                            PhoneNumber = "531-555-0183",
                            ZipCode = 98104
                        },
                        new
                        {
                            RenterId = 24,
                            Address = "80 Sunview Terrace",
                            Email = "jill0@adventure-works.com",
                            FName = "Jill",
                            LName = "Williams",
                            PhoneNumber = "510-555-0121",
                            ZipCode = 55802
                        },
                        new
                        {
                            RenterId = 25,
                            Address = "9178 Jumping St.",
                            Email = "james1@adventure-works.com",
                            FName = "James",
                            LName = "Hamilton",
                            PhoneNumber = "870-555-0122",
                            ZipCode = 75201
                        },
                        new
                        {
                            RenterId = 26,
                            Address = "5725 Glaze Drive",
                            Email = "peter0@adventure-works.com",
                            FName = "Peter",
                            LName = "Krebs",
                            PhoneNumber = "913-555-0196",
                            ZipCode = 94109
                        },
                        new
                        {
                            RenterId = 27,
                            Address = "2487 Riverside Drive",
                            Email = "jo0@adventure-works.com",
                            FName = "Jo",
                            LName = "Brown",
                            PhoneNumber = "632-555-0129",
                            ZipCode = 84407
                        },
                        new
                        {
                            RenterId = 28,
                            Address = "9228 Via Del Sol",
                            Email = "guy1@adventure-works.com",
                            FName = "Guy",
                            LName = "Gilbert",
                            PhoneNumber = "320-555-0195",
                            ZipCode = 85004
                        },
                        new
                        {
                            RenterId = 29,
                            Address = "8291 Crossbow Way",
                            Email = "mark1@adventure-works.com",
                            FName = "Mark",
                            LName = "McArthur",
                            PhoneNumber = "417-555-0154",
                            ZipCode = 38103
                        },
                        new
                        {
                            RenterId = 30,
                            Address = "9707 Coldwater Drive",
                            Email = "britta0@adventure-works.com",
                            FName = "Britta",
                            LName = "Simon",
                            PhoneNumber = "955-555-0169",
                            ZipCode = 32804
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.ReservationModel", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("RenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReserveDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("TaxRate")
                        .HasColumnType("double");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double");

                    b.HasKey("ReservationId");

                    b.HasIndex("CarId");

                    b.HasIndex("RenterId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("CarRentalApp.Models.UserModel", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CarRentalApp.Models.ReservationModel", b =>
                {
                    b.HasOne("CarRentalApp.Models.CarModel", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalApp.Models.RenterModel", "Renter")
                        .WithMany("RentedCar")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Renter");
                });

            modelBuilder.Entity("CarRentalApp.Models.RenterModel", b =>
                {
                    b.Navigation("RentedCar");
                });
#pragma warning restore 612, 618
        }
    }
}
